name: Test csv-generator

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Generate Bundle
      run: |
        git submodule init
        git submodule update
        docker build -t common-templates-ci ./builder/
        docker run \
          -v "$(pwd)":/common-templates \
          common-templates-ci \
          /bin/bash -c "cd /common-templates && export REVISION=1 && make release"