on:
  release:
    types: [published]

name: Publish Bundle

jobs:
  build:
    name: Publish Bundle
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ steps.get_release.outputs.tag_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Generate Bundle
        run: |
          export REVISION=1
          make release

      - name: Upload Release Asset
        id: upload-bundle-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dist/common-templates-$VERSION.yaml
          asset_name: common-templates-$VERSION.yaml
          asset_content_type: text/plain

        - name: Update SSP Operator
          run: |
            git clone https://github.com/omeryahud/ssp-operator
            cd ssp-operator
            git checkout -b update-common-templates-$VERSION
            cp ../dist/common-templates-$VERSION.yaml data/common-templates-bundle/common-templates-$VERSION.yaml
            cp ../dist/common-templates-$VERSION.yaml internal/operands/common-templates/data/common-templates-bundle/common-templates-$VERSION.yaml
            git add data internal
            git commit -sm "Update common-templates bundle to version $VERSION"
            git push -f --set-upstream origin update-common-templates-$VERSION
            echo ${{ secrets.ACTIONS_TOKEN }} > token.txt
            gh auth login < token.txt
            rm token.txt
            gh pr create --repo omeryahud/ssp-operator --base master --head update-common-templates-$VERSION --body 'Update common-templates bundle' --title 'Update common-templates'
            gh auth logout
